name: PardoesCraft
description: hoi
version: 0.03
author: Michel
main: me.mickerd.pardoes.core.main.main
commands:
   villa:
      description: hoi!
   pc:
      description: hoi!
   verwonder:
      description: hoi!
   warp:
      description: hoi!
   socialspy:
      description: hoi!
   title:
      description: hoi!